/**
 * Bundles every book's manifest + lesson JSON under content/ into a single
 * TypeScript module the standalone (single-file) build can import directly,
 * so the app has no filesystem/network dependency at runtime.
 *
 * Usage: npx tsx scripts/generate-standalone-content.ts
 */
import fs from "node:fs";
import path from "node:path";
import type { BookManifest, Lesson } from "./content-pipeline/types";

const CONTENT_ROOT = path.join(process.cwd(), "content");
const OUT_FILE = path.join(process.cwd(), "standalone", "content-data.ts");

function loadBook(slug: string): { manifest: BookManifest; lessons: Record<string, Lesson> } | null {
  const manifestPath = path.join(CONTENT_ROOT, slug, "manifest.json");
  if (!fs.existsSync(manifestPath)) return null;
  const manifest: BookManifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));

  const lessons: Record<string, Lesson> = {};
  const lessonsDir = path.join(CONTENT_ROOT, slug, "lessons");
  if (fs.existsSync(lessonsDir)) {
    for (const partDir of fs.readdirSync(lessonsDir)) {
      const partPath = path.join(lessonsDir, partDir);
      if (!fs.statSync(partPath).isDirectory()) continue;
      for (const file of fs.readdirSync(partPath)) {
        if (!file.endsWith(".json")) continue;
        const lesson: Lesson = JSON.parse(fs.readFileSync(path.join(partPath, file), "utf-8"));
        lessons[`${slug}:${lesson.partIndex}:${lesson.sectionIndex}`] = lesson;
      }
    }
  }
  return { manifest, lessons };
}

function run() {
  if (!fs.existsSync(CONTENT_ROOT)) {
    throw new Error(`No content directory found at ${CONTENT_ROOT}`);
  }
  const slugs = fs
    .readdirSync(CONTENT_ROOT)
    .filter((slug) => fs.existsSync(path.join(CONTENT_ROOT, slug, "manifest.json")));

  const manifests: BookManifest[] = [];
  const allLessons: Record<string, Lesson> = {};

  for (const slug of slugs) {
    const book = loadBook(slug);
    if (!book) continue;
    manifests.push(book.manifest);
    Object.assign(allLessons, book.lessons);
    console.log(`Bundled "${book.manifest.title}": ${Object.keys(book.lessons).length} lessons`);
  }

  const banner = "// AUTO-GENERATED by scripts/generate-standalone-content.ts - do not edit by hand.\n";
  const source = `${banner}import type { BookManifest, Lesson } from "../scripts/content-pipeline/types";

export const manifests: BookManifest[] = ${JSON.stringify(manifests)};

export const lessons: Record<string, Lesson> = ${JSON.stringify(allLessons)};
`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, source);
  console.log(`\nWrote ${OUT_FILE} (${(source.length / 1024 / 1024).toFixed(2)} MB)`);
}

run();
